- CHANGELOG.md
- Cargo.toml
- src/ios.rs
- src/lib.rs
- src/macos.rs
- src/unix.rs
- src/windows.rs
...which makes this crate usable. Also releases `0.1.2` to crates.io.
> Fix non-exhaustive implementation preventing platform structs from being created``

- src/lib.rs
- src/web.rs
Old PR:
This will probably not be the final change, because it:
- A) will probably require bikeshedding as to the proper way to choose between stdweb / web-sys at compile time
- B) does not implement 'empty'
- C) most importantly, removes 'Copy' from the public API of the RawWindowHandle
Some aspect of web support does need to make it into raw-window-handle for web support in winit, but I wanted to put up this PR to start discussion on what that should look like.
Edit: For more context, the Canvas objects in stdweb and web-sys are Clone but not copy, so a struct containing them may not be Copy either. I'm not sure of the best-practice way to work around this.
---
New PR:
A backend-agnostic numerical ID for web has been added as an option to the window handle enum, with documentation …
> Web support via stdweb and web-sys

- src/android.rs
- src/unix.rs
- src/windows.rs
Should solve possible confusion due to the usage of base types.
Fixes https://github.com/rust-windowing/raw-window-handle/issues/11
> Rename XcbHandle surface to window and extend documentation

- src/lib.rs
Addresses https://github.com/rust-windowing/raw-window-handle/issues/14#issuecomment-538686317
> Add clause to documentation clarifying the semantics of null values

- CHANGELOG.md
- src/lib.rs
Reverts #29 and requires that `RawWindowHandle`s be valid for the lifetime of the `HasRawWindowHandle` implementer. Closes #35.
> Various soundness fixes

- CHANGELOG.md
- Cargo.toml
0.3.0 will be yanked after this is merged.
> Release 0.3.1

- src/ios.rs
- src/lib.rs
- src/macos.rs
- src/unix.rs
- src/web.rs
- src/windows.rs
There is no reason for `RawWindowHandle` not to implement it, as it contains only integers and raw pointers. It already implements `Eq`, so it would be possible to store handles in a `HashMap`, which is what I needed in my code.
> Derive Hash implementation

- src/android.rs
Small PR, Android Handle was missed in https://github.com/rust-windowing/raw-window-handle/pull/39 so does not compile on Android.
> Add Hash to Android Handle

- src/lib.rs
Add a wrapper to mark when a specific raw window handle is to be trusted.
Closes https://github.com/rust-windowing/raw-window-handle/issues/49
> add TrustedHandle type

- Cargo.toml
- src/android.rs
- src/ios.rs
- src/macos.rs
- src/unix.rs
- src/windows.rs
This PR completely removes the dependency on `libc`.
It was used to get a `c_void` type, but core::ffi::c_void is sufficient.
It was also used to get `c_ulong`, but we can simply define the type ourselves in the one location that requires it.
Closes https://github.com/rust-windowing/raw-window-handle/issues/3
> Remove the dependency on libc

- src/lib.rs
This seems to be the first step to have latest Mozilla Firefox building on Solaris again. Though Solaris doesn't support Wayland.
> Add basic support for Solaris

- CHANGELOG.md
- src/android.rs
- src/ios.rs
- src/lib.rs
- src/macos.rs
- src/windows.rs
- Encode nullable fields of the handle types in the typesystem (`Option<NonNull<_>>`). The current change is not exhaustive as I'm not familiar with some platforms (e.g Web)
- Adjust docs to allow platform cases where the handles may need to be invalidated over time or further gated by platform specifics like winit/android.
Fixes https://github.com/rust-windowing/raw-window-handle/issues/54
> Explicitly mark fields which may be null

- CHANGELOG.md
- src/android.rs
- src/ios.rs
- src/lib.rs
- src/macos.rs
- src/redox.rs
- src/unix.rs
- src/web.rs
- src/windows.rs
Remove `_non_exhaustive` fields and replace them with the new `#[non_exhaustive]` macro
- Disallow users to use this field anyway, which limit future breaking changes
- Cleaner
- Rust version support is reduced to 1.40+ (I didn't see any notice about that so it may be fine)
- Breaking change
- Disallow `let handle = Handle { /* fields */ ..Handle::empty() };` syntax
Maybe provide a `Handle::new(...)` function for each type ?
> Remove _non_exhaustive fields to use #[non_exhaustive] macro

- src/lib.rs
- src/windows.rs
Currently this crate lacks an entry for Windows WinRT, which uses CoreWindow instead of HWND and other Win32 stuff for handling the windowing.
This pull request implements the `WinRT` variant on `RawWindowHandle`, holding ` WinRTHandle` struct. The `WinRTHandle` struct currently has a single member, `core_window`, which is intended to contain a pointer to a `CoreWindow` instance. This implementation is chosen to match SDL2 which also exposes only the `CoreWindow`, and because it is the minimum currently needed for creating a swapchain on DX12 under WinRT [see here](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgifactory2-createswapchainforcorewindow).
I just copy pasted the existing `Windows` variant, renamed it and replaced the struct members.
> Add WinRT CoreWindow handle

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/redox.rs
We've got some breaking changes building up and it's time to move to a 0.4
---
* Closes https://github.com/rust-windowing/raw-window-handle/issues/63
* Closes https://github.com/rust-windowing/raw-window-handle/issues/60
* Closes https://github.com/rust-windowing/raw-window-handle/issues/58
> Get ready for 0.4

- CHANGELOG.md
- src/lib.rs
Lower bounds of `HasRawWindowHandle` impls of `Arc` and `Rc` to allow unsized types.
This allows to use eg `Arc<dyn HasRawWindowHandle + Send + Sync>`, which is nice to avoid generics.
However this is not done on references because it is a fundamental type, so lowering the bound is a breaking change.
> Allow unsized handle types for `Arc` and `Rc`

- CHANGELOG.md
- Cargo.toml
- src/android.rs
- src/ios.rs
- src/lib.rs
- src/macos.rs
- src/unix.rs
- src/web.rs
- src/windows.rs
~This PR is opened against `master`, but in reality it should be merged into 5207e99a5872e06de2807f556222d056703af44a.~
Using the [semver trick](https://github.com/dtolnay/semver-trick), we can make upgrading from `0.3` to `0.4.1` much less painful!
We simply add a `v0.3` `HasRawWindowHandle` impl for a `v0.4.1` `HasRawWindowHandle`, and release `v0.3.4`.
The idea is that this will allow crates whose purpose is to provide an `HasRawWindowHandle` implementation to upgrade first (e.g. `winit`, `sdl2`, `glfw`, `fltk`, ...). When a sufficient amount of "provider" crates have upgraded, "consumer" crates (e.g. `gfx`, `wgpu`, `rfd`, ...) can safely start upgrading while minimizing breakage for downstream users.
> Alleviate the need for ecosystem-wide upgrading to 0.4.1

- Cargo.toml
- src/lib.rs
Closes #77 
Test with
```sh
RUSTDOCFLAGS='--cfg docsrs' cargo +nightly rustdoc --all-features
```
> Document `HasRawWindowHandle` impl for `Arc` and `Rc` on docs.rs

- CHANGELOG.md
- Cargo.toml
Release `v0.3.4`, which includes the semver trick to make upgrading to `v0.4` easier.
See https://github.com/rust-windowing/raw-window-handle/pull/74#issuecomment-974023212 for more info.
I'll try to keep the changelog date updated in case you, @Lokathor, don't have time to release it today.
> Release `v0.3.4`

- src/unix.rs
Needed for Vulkan physical device presentation support queries (e.g. [`vkGetPhysicalDeviceXlibPresentationSupportKHR`](https://khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceXlibPresentationSupportKHR.html)).
I'm not sure what, if anything, would be a sensible default value for these that won't cause fallout if someone tries to use it. Do we try to solve that problem in general?
> Add visual IDs to X11 handles

- src/web.rs
Not all people reading the documentation will know what a data attribute is (I didn't), and may assume that this just means a regular attribute.
> Add a link to the MDN page for data attributes in the documentation for `WebHandle`

- CHANGELOG.md
- README.md
- src/android.rs
- src/appkit.rs
- src/haiku.rs
- src/lib.rs
- src/redox.rs
- src/uikit.rs
- src/unix.rs
- src/web.rs
- src/windows.rs
On free platforms there're usually multiple displays, so APIs like
EGL have a concept of native display when creating EGLDisplay.
Sometimes creating EGLDisplay must be done before creating the window
on that particular display, to supply e.g. X11 visual information to
the window that will be created on that display later on.
> Decouple display and window from `RawWindowHandle`

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
Note that the intention here is that bumping MSRV is _not_ a breaking change! An example:
- We release `v0.5.1` with the `rust-version` field specified.
- Later on, we change something such that a newer Rust version is required; we bump `rust-version`, and release `v0.5.2`
- Users using Rust 1.56 will automatically choose `v0.5.1`
EDIT: Forget that.
> Specify MSRV

- src/lib.rs
I came to this crate after reading about the recent changes to [`glutin`][0]. At a glance I didn't understand the difference between `RawWindowHandle` and `RawDisplayHandle` (or even what a display was), and the enums looked mostly the same.
After reading through this [issue][1] and digging through the structs, I have a better understanding of what each type represents, but I thought it would be useful to add a line clarifying the distinction between the two. I also added some examples of what external types may be represented for a few platforms.
[0]: https://github.com/rust-windowing/glutin/releases/tag/v0.30.0
[1]: https://github.com/rust-windowing/raw-window-handle/issues/92
> Expand documentation of RawDisplayHandle

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/unix.rs
This bumps MSRV to 1.64 along the way.
Fixes #103.
--
It seems that `wgpu`(already 1.64) and friends are moving towards the `1.64`. In general rust considers MSRV bump as not breaking for 'stable - 2' (including stable).
> Remove `cty` dependency

- CHANGELOG.md
https://github.com/rust-windowing/raw-window-handle/pull/110#issuecomment-1474425418
Should I also bump the version?
> Add #110 to the changelog

- src/borrowed.rs
Forgot to do this the first time around. Makes sure that these traits can be used from reference as well.
> feat: Implement HasDisplayHandle and HasWindowHandle on reference types

- Cargo.toml
- src/borrowed.rs
- src/lib.rs
The previous implementation is unsound in several cases. This PR ensures that window handles don't outlive the application.
Draft until I can verify that it actually works. Supersedes #114
> Change the "Active" struct to be sound

- .github/workflows/ci.yml
- src/lib.rs
Guards borrowed handles behind either `std` or not being on Android. Should prevent this from being a breaking change.
Another possible way around this would be to add a `borrowed` feature.
> Restrict compilation of borrowed handles on Android

- CHANGELOG.md
- src/borrowed.rs
- src/lib.rs
This is a breaking change. Supersedes #104.
> Make raw_*_handle return a result

- CHANGELOG.md
- src/borrowed.rs
- src/lib.rs
Since it's unnecessary and #122 is a breaking change anyways.
> Remove Active from the API

- src/borrowed.rs
Derives `Hash`, `PartialEq`, `Eq`, `Copy` and `Clone` for both borrowed handles.
> Make sure traits are uniform across WindowHandle and DisplayHandle

- src/borrowed.rs
- src/lib.rs
As the traits are implemented for `&T` where `T` implements the traits, I'm not sure why they can't also be implemented for `&mut T`.
> Implement traits for &mut T

- CHANGELOG.md
- src/appkit.rs
- src/uikit.rs
The window can easily be fetched from the view, and having it leads to confusion over which place you should be e.g. taking the drawing dimensions (always the view).
Part of https://github.com/rust-windowing/raw-window-handle/issues/123
> Remove window handles from Apple handles

- src/unix.rs
- src/windows.rs
In similar spirit as https://github.com/rust-windowing/raw-window-handle/pull/136.
I'm not sure myself that this is such a good idea, mainly because:
- The `c_int/c_long` types are not possible to convert to non-zero types in the same manner (leading to us only using the API in some places).
- Ensuring non-null pointers is _important_, since that causes unsoundness if used incorrectly, while a zero handle isn't that big of a problem, any operations you do on them will just error (just like any other invalid handle).
Other options would be to panic on `0` in the constructor (a weak check against invalid handles, assuming those are exceedingly rare), or we could document that it is a bug in the implementer (as opposed to the consumer) to provide zero handles where unexpected?
> Make integer handles use non-zero types

- CHANGELOG.md
- src/borrowed.rs
- src/lib.rs
> Remove `Copy` for `RawWindowHandle`/`WindowHandle`

- CHANGELOG.md
- src/android.rs
- src/appkit.rs
- src/haiku.rs
- src/lib.rs
- src/redox.rs
- src/uikit.rs
- src/unix.rs
- src/web.rs
- src/windows.rs
A _lot_ of consumers of `raw-window-handle` assume that the pointers are non-null, which makes those libraries unsound. Since the traits are fallible nowadays, we should try to use the type-system to ensure that the handles are always completely valid, instead of expecting user to check it themselves.
This could be done by using `Option<NonNull<c_void>>`, but that still needs the user to unwrap what _should_ always be set anyhow, so I opted for renaming the `empty` methods to `new`, and taking parameters to these where it makes sense. Note that the structs are still left open to non-breaking extensions, as they are still marked `#[non_exhaustive]` - with the caveat that those extensions must be optional / have a sensible default.
See …
> Change how handles are constructed, so that we can ensure non-null handles

- .github/workflows/ci.yml
- src/borrowed.rs
- src/lib.rs
After reading #135, I've realized that the HasRawDisplayHandle and HasRawWindowHandle traits have little value in a post-borrowed-handle world. Borrowed handles do everything better, and the raw handle can be extracted from the borrowed handle. Therefore it makes sense to remove these traits.
Closes #135.
> Excise the HasRaw*Handle traits

- src/android.rs
- src/appkit.rs
- src/haiku.rs
- src/redox.rs
- src/uikit.rs
- src/web.rs
- src/windows.rs
For display handles which are empty, it is safe to create them without
any borrowing considerations. This may be useful to windowing
frameworks with entirely safe code.
cc #156
> Safe constructors for some display handles

- src/appkit.rs
- src/uikit.rs
This takes part of the main thread only docs from https://github.com/rust-windowing/raw-window-handle/pull/154, but with the less strong guarantee of the handle only ever _existing_ on the main thread (as that's probably not yet true in the wild, so I'd rather have consumers to the extra check).
> Improve documentation for UIKit and AppKit handles

- .github/workflows/ci.yml
- README.md
wasm-bindgen recently bumped its MSRV to v1.73, which is much higher
than our MSRV of 1.64. Add an note to the README describing our MSRV
policy, and then test for it in CI.
----
cc @daxpedda
> Add MSRV policy regarding wasm-bindgen

- src/windows.rs
This commit clarifies what is expected by the system for a Win32 handle.
It is expected that the Win32 handle belongs to the current thread. This
is not a breaking change as it was previously necessary for the window
to be considered "valid".
cc https://github.com/rust-windowing/winit/pull/3593
> Clarify Win32 handle validity

- src/appkit.rs
- src/uikit.rs
Damn, should've pushed this before #165, but oh well.
> Update documentation to refer to new objc2 crates

- src/lib.rs
- src/ohos.rs
Add support for the [OpenHarmony] operating system, which is a [tier-2 target] in Rust starting with
Rust 1.78.
On OpenHarmony [ArkUI] is used to develop
applications. ArkUI provides the [XComponent]
type, which allows native code (e.g. Rust) to use
EGL / OpenGL ES to render directly to a native
window.
[tier-2 target]: https://doc.rust-lang.org/nightly/rustc/platform-support/openharmony.html
[OpenHarmony]: https://gitee.com/openharmony/docs/blob/master/en/OpenHarmony-Overview.md
[ArkUI]: https://gitee.com/openharmony/docs/blob/master/en/application-dev/ui/arkui-overview.md
[XComponent]: https://gitee.com/openharmony/docs/blob/master/en/application-dev/ui/arkts-common-components-xcomponent.md
> Add OpenHarmony OS support

- CHANGELOG.md
- Cargo.toml
It would be nice (for me) if there could be a new Release containing #164.
I just went ahead and put todays date in the Changelog, but I can also change it to `## unreleased` or something else.
> Update Changelog and bump version number

- CHANGELOG.md
- src/appkit.rs
- src/lib.rs
- src/uikit.rs
- Update availability hints to include visionOS.
- Use objc2 v0.6 in examples.
- Add more detailed examples of how to create UIKit and AppKit handles.
> Improve documentation on AppKit and UIKit variants 

- CHANGELOG.md
- src/uikit.rs
This can be retrieved from the `UIView` itself, and is hence unnecessary information for us to carry around.
Besides, since it's optional, users that want to get the view controller has to do the searching logic anyways.
Once we remove this in the next breaking version, we should move the example code I've provided on `ui_view_controller` here to an example instead.
> Deprecate `UiKitWindowHandle::ui_view_controller`
